export {default as Blog} from './blogs/Blog'
export {default as Header} from './header/Header'
export {default as About} from './about/About'
export {default as Work} from './Work/Work'
export {default as Footer} from './footer/Footer'
// export {default as Feature} from './features/Feature' 
export {default as Reviews} from './Reviews/Reviews' 